/**
 * Created by ZhouYun on 2016/12/8.
 */
define([],function(){
  return {
    baseUrl:'/js',
    text:{
      env:'rhino'
    },
    paths:{
      'jquery':'plugin/jquery',
      'mock':'plugin/mock',
      'sha1':'plugin/sha1',
      'template7':'plugin/template7',
      'slider':'plugin/unslider',
      'tool':'module/tool',
      'zh_tips':'module/zh_tips',
      'text':'module/text'
    },
    shim:{
      'jquery':{
        'exports':'$'
      },
      'slider':['jquery'],
      'sha1':['jquery'],
      'template7':{
        'exports':'Template7'
      }
    }
  };
});